### ISSUE TITLE
Cant see the see the my profile btn in products page

### ISSUE THREAD

**Issue by Sandeepsan97** [fssa-batch3/prathiusha.sakthivel__web_project#4]
### Description of issue
Cant see the see the my profile btn in products page

### Expected result
After clicking the next btn in profile page it is redirecting to product page and it should show the my profile btn in product page.

### Actual result
After clicking the next btn in profile page it is redirecting to product page and it  is showing  the sign up and register  btn in product page.

### Steps to reproduce
1. By using the  info of  the login user  in local storage and make the page according to it 
2. 
3. 

```
Path:      /html/veges.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2Fhtml%2Fveges.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/html/veges.html)

**Comment by prathiusha22** [comment]
I have cleared this bug.

**Comment by prathiusha22** [comment]
I have cleared this "Cant see the see the my profile btn in products page" bug.

**Comment by Sandeepsan97** [comment]
issue solved
