### ISSUE TITLE
Delete btn if click delete it is deleting account one by one

### ISSUE THREAD

**Issue by Sandeepsan97** [fssa-batch3/prathiusha.sakthivel__web_project#5]
### Description of issue
Delete btn if click delete it is deleting account one by one 

### Expected result
It should delete the account of the user who logged in 

### Actual result
It should delete the account of the user who logged in but it is also deleting another user account  if i click  delete btn again 

### Steps to reproduce
1. You can use login local storage to make the  account delete by unique details 
2. 
3. 

```
Path:      /html/profilepage.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2Fhtml%2Fprofilepage.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/html/profilepage.html)

**Comment by prathiusha22** [comment]
I solved Delete btn if click delete it is deleting account one by one

**Comment by prathiusha22** [comment]
I have taken the delete button and instead of delete button I have changed it into log out button.

**Comment by Sandeepsan97** [comment]
solved
