### ISSUE TITLE
No login or register button on the home page of the website

### ISSUE THREAD

**Issue by santhanam13** [fssa-batch3/prathiusha.sakthivel__web_project#6]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNDgzYmVkYjktYTg1Mi00NzM1LTg0OWUtNDYzNWRiZTk0NTUzIiwiZGVwbG95X2lkIjoiNjQ0NTA5MDQ3NTRlODcwMDA4MjEzN2QwIiwiaWQiOiJjMDMwZmUxNC05Zjk0LTRjYmUtODlkZS1iMzgzMjBiNGEyMWEifQ==)

### Description of issue
- In the home page of the website there is no login or sing up button to create account or login into our account.

### Expected result
- User creating account on the home page of the website.

### Actual result
- The user can't find the login or sing up button the home page.

### Steps to reproduce
1. Navigate to the home page of the website.
2. Check for login or sign up button.

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/)

**Comment by prathiusha22** [comment]
I solved this "In the home page of the website there is no login or sing up button to create account or login into our account." issue.

**Comment by santhanam13** [comment]
issue solved
