### ISSUE TITLE
lack of initial  flow in the project

### ISSUE THREAD

**Issue by santhanam13** [fssa-batch3/prathiusha.sakthivel__web_project#7]
### Description of issue
As the index page contains the user registration, the seller should initially login as a user and then as a user which seems logically incorrect.so that why this issue arises

### Expected result
separate user/seller registration in the index page

### Actual result
only user registration in the index page and then only seller page arises

### Steps to reproduce
1. I signup in the index page 
2. I click seller page 
3. There is sign up in the top of the page

```
Path:      /html/bankdet
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2Fhtml%2Fbankdet&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/html/bankdet)

**Comment by prathiusha22** [comment]
I have cleared this bug As the index page contains the user registration, the seller should initially login as a user and then as a user which seems logically incorrect.so that why this issue arises.

**Comment by santhanam13** [comment]
Verified. So i close this issue
