### ISSUE TITLE
 undefined values

### ISSUE THREAD

**Issue by santhanam13** [fssa-batch3/prathiusha.sakthivel__web_project#8]
### Description of issue

shows undefined values

### Expected result
it want to show quantity

### Actual result
showing undefined

### Steps to reproduce
1. register
2. selling page
3. create html

```
Path:      /html/create.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2Fhtml%2Fcreate.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/html/create.html)

**Comment by prathiusha22** [comment]
I have cleared this bug shows undefined values.

**Comment by santhanam13** [comment]
Verified.So i close this issue
