### ISSUE TITLE
bug in add to cart

### ISSUE THREAD

**Issue by santhanam13** [fssa-batch3/prathiusha.sakthivel__web_project#9]
### Description of issue

if i  add to cart without login it didint gave alert or redirected to login page
### Expected result
alert you are not logged it or redirect to login page

### Actual result
page refresh product not added

### Steps to reproduce
1. open the netlify
2. added the product to cart
3. not added or not gave any alert

```
Path:      /index.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--greenfarmz.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--greenfarmz.netlify.app/index.html)

**Comment by prathiusha22** [comment]
I have cleared this bug if I add to cart without login it didn't gave alert or redirected to login page.

**Comment by santhanam13** [comment]
Verified.So i close this issue
